CC     = owcc
PROG   = libopenpmd.exe

SRCS   = libopenpmd.c
OBJS   = libopenpmd.o

CFLAGS  = -s -Wall -Wextra -Werror -std=c89 -bdos

$(PROG): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROG)

libopenpmd.o: libopenpmd.c
	$(CC) $(CFLAGS) -c libopenpmd.c

clean: .procedure
	del $(OBJS)

