name: Project CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run:  cmake -B $PWD/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run:  cmake --build $PWD/build

    - name: Test
      run: |
        cd $PWD/build

        ./tools/Debug/loadtest ../examples/P86/RC1.P86
        mv TEST_MEM.P86 LOADTEST_MEM.P86
        mv TEST_FIL.P86 LOADTEST_FIL.P86

        ./tools/Debug/p86extract LOADTEST_MEM.P86
        ./tools/Debug/p86create TEST.*.RAW
        mv TEST.P86 P86CREATE.P86

        CertUtil -hashfile ../examples/P86/RC1.P86 MD5
        CertUtil -hashfile LOADTEST_MEM.P86 MD5
        CertUtil -hashfile LOADTEST_MEM.P86 MD5
        CertUtil -hashfile P86CREATE.P86 MD5
